# Generated by Django 3.0.8 on 2020-11-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approval',
        ),
    ]
