# Generated by Django 3.0.8 on 2020-11-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0003_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='ContactForm',
        ),
    ]
