# Generated by Django 3.2.3 on 2021-05-25 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myAPI', '0004_auto_20201119_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=60)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('otp', models.CharField(max_length=8)),
                ('aadhaar_card', models.CharField(max_length=14)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(default='NULL', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
