# Generated by Django 3.2.3 on 2021-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0005_patientinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='x_ray',
            field=models.ImageField(default='C:/Users/HP/Documents/Chinnu/major_project_V1/majorProject_V1-main/media/COVID_19.png', upload_to='xray_images'),
        ),
    ]
