# Generated by Django 3.2.3 on 2021-06-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0006_patientinformation_x_ray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
